// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpmtadfofpnfdcatzdse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwbXRhZGZvZnBuZmRjYXR6ZHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODA5MjEsImV4cCI6MjA3MjY1NjkyMX0.u_pufk9N-h3X5aMxkW92d1TiCsGbJQ18ZpqF2P1s4oI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});